name: michaelmusic
description: "App Nghe Nháº¡c Cá»§a Mai Cá»“"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icon máº·c Ä‘á»‹nh
  cupertino_icons: ^1.0.6

  # --- Äá»“ chÆ¡i má»›i cho Mai Cá»“ ---
  just_audio: ^0.9.37
  audio_session: ^0.1.19
  dio: ^5.4.3
  path_provider: ^2.1.3
  rxdart: ^0.27.7
  audio_video_progress_bar: ^2.0.2

  # ðŸ”¥ CHá»ˆ Cáº¦N DÃ’NG NÃ€Y LÃ€ Äá»¦ (ÄÃ£ bao gá»“m thÃ´ng bÃ¡o)
  audio_service: ^0.18.18

  # Permission Handler (Báº£n má»›i nháº¥t OK)
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# Cáº¥u hÃ¬nh Logo
flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/icon-app_256.png"
  min_sdk_android: 21

# Cáº¥u hÃ¬nh Flutter
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/michaelsongs.json
    - assets/itunes_256.png
    - assets/icon-app_256.png